### PR TITLE
Add more Google Smart Home traits, types and commands

### PR DESCRIPTION
**Pull request by qwandor**
I tried generating these automatically from https://github.com/actions-on-google/smart-home-schema with [schemafy](https://crates.io/crates/schemafy), but the output wasn't very nice so I stuck with the manual route for now.

Note that some of the types can no longer be `Eq` because of the `f64` in `Hsv`, but `PartialEq` should be sufficient.

### CODE REVIEW

**Comment by gbaranski** [comment]
What about Commands? It might be hard to auto generate, but some degree of automation would be great.

What about generating structs to this form? It'd still require some manual work.

```rust
/// <command_comment>
struct <command_name> {
    /// <parameter_comment>
    pub <parameter_name>: () // or maybe todo!() instead of ()
    ... // add a field for each parameter
}
```

**Comment by qwandor** [comment]
It looks like it would require some changes to `schemafy` to improve how it generates names, plus a bunch of extra custom code to go through the YAML files and connect everything together. I could look into it more, but I'm not sure whether it's worth the effort. Assign an issue to me if you like.

**Comment by gbaranski** [comment]
that's fine for now, thanks for contributing.

I'll merge that into `feat/add-hub` branch.

**Review by gbaranski — APPROVED** [review]
Looks good to me. Thanks for contribution!

**Pull request merged**
